# NOTE: This file is generated by yotta: changes will be overwritten!

if(YOTTA_META_TOOLCHAIN_FILE_INCLUDED)
    return()
endif()
set(YOTTA_META_TOOLCHAIN_FILE_INCLUDED 1)

{% for toolchain_file in toolchain_files %}
include("{{ toolchain_file | replaceBackslashes }}")
{% endfor %}

